<?php

namespace ViKingMrBoo\ProxyGenerator;

use Doctrine\Common\Annotations\AnnotationReader;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;
use ViKingMrBoo\ProxyGenerator\DependencyInjection\Compiler\ProxyCompilerPass;

class VikingProxyGeneratorBundle extends Bundle
{
    public function build(ContainerBuilder $container)
    {
        // Регистрация компилятора с AnnotationReader
        $annotationReader = new AnnotationReader();
        $container->addCompilerPass(new ProxyCompilerPass($annotationReader));
        parent::build($container); // TODO: Change the autogenerated stub
    }

}