services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  
  ViKingMrBoo\ProxyGenerator\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
  
  ViKingMrBoo\ProxyGenerator\VikingProxyGeneratorService:
    arguments:
      $proxyGenerator: '@doctrine.proxy_generator'
      $annotationReader: '@annotation_reader'
      $cache: '@viking_proxy_generator.proxy_cache_service'

  viking_proxy_generator.proxy_cache_service:
    class: ViKingMrBoo\ProxyGenerator\VikingProxyCacheService
    arguments:
      $cache: '@doctrine.cache.providers.doctrine_file_cache'
  
  ViKingMrBoo\ProxyGenerator\AbstractClient:
    abstract: true
    public: false
  
  ViKingMrBoo\ProxyGenerator\VikingProxyGeneratorBundle:
    public: false